name: Elixir Credo

on: [pull_request]

jobs:
  credo:
    name: Credo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12'

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Git configuration
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Run Credo
        run: mix credo --format=flycheck --all --strict > credo.txt

      - name: Make script executable
        run: chmod +x .github/scripts/credo_to_sarif.sh

      - name: Convert Credo results to SARIF
        run: .github/scripts/credo_to_sarif.sh
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: credo.sarif
